x=input('digite qualquer coisa: ')
print('o tipo primitivo dessa valor é ', type(x))
print('somente espaços: ', x.isspace())
print('é numérico? ', x.isnumeric())
print('é alfabético? ', x.isalpha())
print('é alfanumérico? ', x.isalnum())
print('Está em maiúsculas? ',x.isupper())
print('Está em minúsculas? ',x.islower())
print('Está capitalizada? ',x.istitle())